UPDATE guides
SET platform_version = 'Windows 10 or Windows 11',
    required_tools = 'Stable internet connection\nAt least 10 GB free storage',
    prerequisites = 'Save open work and connect the device to power before installing updates.',
    backup_warning = 'Back up important files before troubleshooting an update that has repeatedly failed.',
    last_reviewed_at = '2026-07-19',
    next_actions = 'If the update still fails, use official Microsoft recovery guidance or contact a qualified technician.'
WHERE slug = 'check-windows-update-issue';

INSERT INTO guides (category_id, title, slug, description, difficulty, estimated_time, risk_level, content, platform_version, required_tools, prerequisites, backup_warning, last_reviewed_at, next_actions, is_published)
SELECT categories.id, seeded.title, seeded.slug, seeded.description, seeded.difficulty, seeded.estimated_time, seeded.risk_level, '', seeded.platform_version, seeded.required_tools, seeded.prerequisites, seeded.backup_warning, '2026-07-19', seeded.next_actions, 1
FROM (
    SELECT 'windows' AS category_slug, 'Fix a Windows Wi-Fi connection problem' AS title, 'fix-windows-wifi-connection' AS slug, 'Restore a Windows connection by checking the device, network, and adapter in a safe order.' AS description, 'Beginner' AS difficulty, '15 to 30 minutes' AS estimated_time, 'Low' AS risk_level, 'Windows 10 or Windows 11' AS platform_version, 'Access to the affected Wi-Fi network\nRouter password if reconnecting' AS required_tools, 'Confirm the router is powered on and save open work before restarting the computer.' AS prerequisites, 'Resetting network settings removes saved Wi-Fi networks and passwords. Record them before using that step.' AS backup_warning, 'If other devices also fail, restart the modem and router or contact the internet provider.' AS next_actions
    UNION ALL SELECT 'android', 'Fix an Android app that crashes or will not open', 'fix-android-app-crashing', 'Use this guide when one Android app closes unexpectedly, freezes, or will not load.', 'Beginner', '10 to 20 minutes', 'Low', 'Android 12 or later', 'Internet connection\nGoogle Play Store access', 'Charge the phone and make sure you can sign in to the affected app if needed.', 'Clearing app data or reinstalling can remove information stored only on the device.', 'Contact the app developer when updates and reinstallation do not solve a one-app problem.'
    UNION ALL SELECT 'android', 'Fix an Android phone that freezes or stops responding', 'fix-android-phone-freezing', 'Troubleshoot whole-device freezes, slowdowns, and repeated restarts.', 'Beginner', '15 to 30 minutes', 'Low', 'Android 12 or later', 'Battery power\nInternet connection', 'Save important work when the phone is responsive.', 'A factory reset removes personal data. Back up files and accounts before considering it.', 'Contact the device manufacturer if the phone still freezes after Safe Mode testing and updates.'
    UNION ALL SELECT 'iphone', 'Fix an iPhone or iPad that cannot connect to Wi-Fi', 'fix-iphone-ipad-wifi-connection', 'Identify whether a Wi-Fi connection problem affects one Apple device or the whole network.', 'Beginner', '10 to 25 minutes', 'Low', 'iOS or iPadOS 17 or later', 'Wi-Fi password\nAccess to the modem and router', 'Know the Wi-Fi password before forgetting a network.', 'Reset Network Settings removes saved networks, passwords, cellular settings, VPN settings, and APN settings.', 'Contact Apple Support or the internet provider when the problem affects only the device or every device respectively.'
    UNION ALL SELECT 'iphone', 'Fix an iPhone or iPad app that closes or will not open', 'fix-iphone-app-crashing', 'Resolve a single iPhone or iPad app that closes, freezes, or does not open.', 'Beginner', '10 to 20 minutes', 'Low', 'iOS or iPadOS 17 or later', 'Internet connection\nApp Store access', 'Confirm you can sign back in to the app if it needs an account.', 'Deleting an app can remove information stored only inside that app.', 'Contact the developer when one updated app still fails after a reinstall.'
    UNION ALL SELECT 'linux', 'Fix Wi-Fi not connecting on Ubuntu', 'fix-ubuntu-wifi-not-connecting', 'Use Ubuntu-specific checks to restore a wireless connection safely.', 'Intermediate', '20 to 40 minutes', 'Low', 'Ubuntu 22.04 LTS or later', 'Terminal\nAnother trusted network or hotspot', 'This guide supports Ubuntu only. Record the Wi-Fi password before forgetting a saved network.', 'Do not download random driver packages or run commands from untrusted websites.', 'Use Ubuntu driver tools or official hardware documentation if the wireless device is not detected.'
    UNION ALL SELECT 'linux', 'Fix Ubuntu package update errors', 'fix-ubuntu-package-update-errors', 'Resolve common Ubuntu update errors without deleting package-manager lock files.', 'Intermediate', '15 to 35 minutes', 'Medium', 'Ubuntu 22.04 LTS or later', 'Terminal\nStable internet connection', 'Close Software Updater, Ubuntu Software, Synaptic, and other package tools first.', 'Do not manually delete package lock files or run commands copied from unknown websites.', 'Stop and consult Ubuntu documentation when errors identify an unsupported repository or a damaged installation.'
    UNION ALL SELECT 'macos', 'Speed up a slow Mac', 'speed-up-slow-mac', 'Use storage, Activity Monitor, login-item, and update checks to improve Mac performance.', 'Beginner', '20 to 40 minutes', 'Low', 'macOS Ventura or later', 'Administrator access for updates', 'Save open documents before restarting or installing updates.', 'Do not delete system files or quit processes you do not recognize in Activity Monitor.', 'Contact Apple Support if Safe Mode does not isolate the problem or the Mac repeatedly restarts.'
    UNION ALL SELECT 'macos', 'Fix a macOS update or installation error', 'fix-macos-update-installation-error', 'Prepare safely for a macOS update retry and know when recovery support is appropriate.', 'Intermediate', '30 to 90 minutes', 'Medium', 'macOS Ventura or later', 'Backup drive\nStable internet connection\nPower adapter', 'Back up important files and connect portable Macs to power before starting.', 'Do not erase the Mac unless a verified backup exists and safer recovery options have failed.', 'Contact Apple Support for persistent firmware, recovery, or installation failures.'
    UNION ALL SELECT 'wifi', 'Fix Wi-Fi that keeps disconnecting', 'fix-wifi-keeps-disconnecting', 'Separate device, wireless, modem, router, and provider causes of repeated disconnects.', 'Beginner', '20 to 40 minutes', 'Low', 'Home Wi-Fi router', 'Router administration access\nEthernet cable when available', 'Record the Wi-Fi name and password before changing router settings.', 'Do not factory-reset the router until its configuration and provider details are recorded.', 'Contact the internet provider when wired devices also lose service.'
    UNION ALL SELECT 'wifi', 'Fix connected to Wi-Fi but no internet', 'fix-wifi-connected-no-internet', 'Determine whether missing internet access is caused by one device, the router, modem, VPN, DNS, or provider.', 'Beginner', '15 to 35 minutes', 'Low', 'Home Wi-Fi router', 'Router administration access\nEthernet cable when available', 'Test more than one website before changing any network setting.', 'Changing DNS or resetting the router can interrupt service. Use those actions only after basic checks.', 'Contact the internet provider when all wired and wireless devices cannot reach the internet.'
) AS seeded
JOIN categories ON categories.slug = seeded.category_slug
ON DUPLICATE KEY UPDATE
    title = VALUES(title), description = VALUES(description), difficulty = VALUES(difficulty), estimated_time = VALUES(estimated_time), risk_level = VALUES(risk_level), content = VALUES(content), platform_version = VALUES(platform_version), required_tools = VALUES(required_tools), prerequisites = VALUES(prerequisites), backup_warning = VALUES(backup_warning), last_reviewed_at = VALUES(last_reviewed_at), next_actions = VALUES(next_actions), is_published = VALUES(is_published);

INSERT INTO guide_tools (guide_id, name, sort_order)
SELECT guides.id, seeded.name, seeded.sort_order
FROM guides
JOIN (
    SELECT 'check-windows-update-issue' AS guide_slug, 'Stable internet connection' AS name, 1 AS sort_order UNION ALL
    SELECT 'check-windows-update-issue', 'At least 10 GB free storage', 2 UNION ALL
    SELECT 'fix-windows-wifi-connection', 'Wi-Fi password', 1 UNION ALL
    SELECT 'fix-windows-wifi-connection', 'Router access', 2 UNION ALL
    SELECT 'fix-android-app-crashing', 'Google Play Store access', 1 UNION ALL
    SELECT 'fix-android-phone-freezing', 'Battery power', 1 UNION ALL
    SELECT 'fix-iphone-ipad-wifi-connection', 'Wi-Fi password', 1 UNION ALL
    SELECT 'fix-iphone-app-crashing', 'App Store access', 1 UNION ALL
    SELECT 'fix-ubuntu-wifi-not-connecting', 'Terminal', 1 UNION ALL
    SELECT 'fix-ubuntu-package-update-errors', 'Terminal', 1 UNION ALL
    SELECT 'speed-up-slow-mac', 'Administrator access', 1 UNION ALL
    SELECT 'fix-macos-update-installation-error', 'Backup drive', 1 UNION ALL
    SELECT 'fix-wifi-keeps-disconnecting', 'Router administration access', 1 UNION ALL
    SELECT 'fix-wifi-connected-no-internet', 'Ethernet cable when available', 1
) AS seeded ON seeded.guide_slug = guides.slug
ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO guide_sources (guide_id, title, official_url, trusted_source_domain_id, source_last_reviewed_at, sort_order)
SELECT guides.id, seeded.title, seeded.official_url, trusted_source_domains.id, trusted_source_domains.last_reviewed_at, 1
FROM guides
JOIN (
    SELECT 'check-windows-update-issue' AS guide_slug, 'Microsoft Windows Update support' AS title, 'https://support.microsoft.com/' AS official_url, 'support.microsoft.com' AS domain UNION ALL
    SELECT 'fix-windows-wifi-connection', 'Microsoft Wi-Fi support', 'https://support.microsoft.com/windows', 'support.microsoft.com' UNION ALL
    SELECT 'fix-android-app-crashing', 'Google Android Help', 'https://support.google.com/android/answer/2668665', 'support.google.com' UNION ALL
    SELECT 'fix-android-phone-freezing', 'Google Android Help', 'https://support.google.com/android/answer/7664448', 'support.google.com' UNION ALL
    SELECT 'fix-iphone-ipad-wifi-connection', 'Apple Support', 'https://support.apple.com/111786', 'support.apple.com' UNION ALL
    SELECT 'fix-iphone-app-crashing', 'Apple Support', 'https://support.apple.com/119876', 'support.apple.com' UNION ALL
    SELECT 'fix-ubuntu-wifi-not-connecting', 'Ubuntu Desktop Guide', 'https://help.ubuntu.com/stable/ubuntu-help/net-wireless-troubleshooting.html', 'help.ubuntu.com' UNION ALL
    SELECT 'fix-ubuntu-package-update-errors', 'Ubuntu Desktop Guide', 'https://help.ubuntu.com/stable/ubuntu-help/', 'help.ubuntu.com' UNION ALL
    SELECT 'speed-up-slow-mac', 'Apple Support', 'https://support.apple.com/guide/mac-help/mchlp1731/mac', 'support.apple.com' UNION ALL
    SELECT 'fix-macos-update-installation-error', 'Apple Support', 'https://support.apple.com/102531', 'support.apple.com' UNION ALL
    SELECT 'fix-wifi-keeps-disconnecting', 'TP-Link Support', 'https://www.tp-link.com/uk/support/faq/722/', 'www.tp-link.com' UNION ALL
    SELECT 'fix-wifi-connected-no-internet', 'Google Nest Help', 'https://support.google.com/googlenest/answer/9239960', 'support.google.com'
) AS seeded ON seeded.guide_slug = guides.slug
JOIN trusted_source_domains ON trusted_source_domains.domain = seeded.domain
ON DUPLICATE KEY UPDATE title = VALUES(title), trusted_source_domain_id = VALUES(trusted_source_domain_id), source_last_reviewed_at = VALUES(source_last_reviewed_at), sort_order = VALUES(sort_order);

INSERT INTO guide_steps (guide_id, step_number, step_title, step_text, expected_result, warning_text, recovery_text)
SELECT guides.id, seeded.step_number, seeded.step_title, seeded.step_text, seeded.expected_result, seeded.warning_text, seeded.recovery_text
FROM guides
JOIN (
    SELECT 'check-windows-update-issue' AS guide_slug, 1 AS step_number, 'Restart before changing settings' AS step_title, 'Restart the computer and try Windows Update again.' AS step_text, 'Windows starts normally and Windows Update can be tried again.' AS expected_result, 'Save unsaved work before restarting.' AS warning_text, 'If Windows cannot restart normally, stop and use official recovery guidance.' AS recovery_text UNION ALL
    SELECT 'check-windows-update-issue', 2, 'Check connection and storage', 'Confirm that the device has a stable internet connection and enough free storage.', 'The device has a reliable connection and enough room for the update.', 'Do not delete system files to create storage space.', 'If storage cannot be freed safely, back up files before removing personal content.' UNION ALL
    SELECT 'fix-windows-wifi-connection', 1, 'Check the network scope', 'Test another website and another device on the same Wi-Fi network.', 'You know whether the problem affects one computer or the whole network.', '', 'Continue with the Windows checks when only this computer is affected.' UNION ALL
    SELECT 'fix-windows-wifi-connection', 2, 'Forget and reconnect', 'Open Wi-Fi settings, forget the saved network, and reconnect with the correct password.', 'Windows connects and receives internet access.', 'Record the Wi-Fi password before forgetting the network.', 'Restart the modem and router when other devices also fail.' UNION ALL
    SELECT 'fix-windows-wifi-connection', 3, 'Run the Windows troubleshooter', 'Open Settings, choose System, Troubleshoot, Other troubleshooters, then run Network and Internet.', 'Windows identifies or repairs a common adapter setting problem.', '', 'Use official Microsoft support when the adapter remains unavailable.' UNION ALL
    SELECT 'fix-android-app-crashing', 1, 'Restart the phone', 'Save open work and restart the phone normally.', 'The app opens and works normally after restart.', '', 'Continue to update the app.' UNION ALL
    SELECT 'fix-android-app-crashing', 2, 'Update the affected app', 'Open Google Play Store, choose Manage apps and devices, and install the available app update.', 'The updated app opens without crashing.', '', 'Install Android updates next.' UNION ALL
    SELECT 'fix-android-app-crashing', 3, 'Clear cache or reinstall', 'Open the app storage settings and clear its cache. Reinstall only after confirming important app data is synchronized.', 'Temporary files are removed or a clean installation opens correctly.', 'Reinstalling can remove locally stored app data.', 'Contact the app developer if only this updated app still fails.' UNION ALL
    SELECT 'fix-android-phone-freezing', 1, 'Force restart the phone', 'Hold the power button for about 30 seconds. Some manufacturers use a power and volume-button combination.', 'The phone restarts and responds normally.', '', 'Install Android and app updates if freezes continue.' UNION ALL
    SELECT 'fix-android-phone-freezing', 2, 'Check storage and updates', 'Open Settings, review storage, remove unneeded downloads, and install available Android and app updates.', 'The phone has free space and current fixes installed.', 'Do not remove important files without a backup.', 'Test Safe Mode if the problem continues.' UNION ALL
    SELECT 'fix-android-phone-freezing', 3, 'Test Safe Mode', 'Use the manufacturer Safe Mode instructions, then remove recently installed apps one at a time if the phone works normally.', 'You identify whether a downloaded app is responsible.', 'A factory reset removes data and is not a first troubleshooting step.', 'Contact the manufacturer before considering a factory reset.' UNION ALL
    SELECT 'fix-iphone-ipad-wifi-connection', 1, 'Confirm Wi-Fi and test another device', 'Open Settings, confirm Wi-Fi is on and Airplane Mode is off, then test another device on the same network.', 'You know whether the issue is limited to this device.', '', 'Restart the iPhone or iPad when only it is affected.' UNION ALL
    SELECT 'fix-iphone-ipad-wifi-connection', 2, 'Restart the device and network', 'Restart the iPhone or iPad. If every device is affected, restart the modem first and the router after its lights stabilize.', 'The device reconnects to Wi-Fi and internet access returns.', '', 'Test another trusted Wi-Fi network.' UNION ALL
    SELECT 'fix-iphone-ipad-wifi-connection', 3, 'Reset network settings last', 'Open Settings, General, Transfer or Reset, Reset, then Reset Network Settings.', 'The device can reconnect after entering the Wi-Fi password again.', 'This removes saved Wi-Fi, cellular, VPN, and APN settings.', 'Contact Apple Support if the problem follows the device to another network.' UNION ALL
    SELECT 'fix-iphone-app-crashing', 1, 'Close and reopen the app', 'Close the unresponsive app, open it again, then restart the iPhone or iPad if needed.', 'The app opens and responds normally.', '', 'Install app updates if it still closes.' UNION ALL
    SELECT 'fix-iphone-app-crashing', 2, 'Update the app and system', 'Open the App Store profile to install app updates, then install any iOS or iPadOS update in Settings.', 'The app runs with current compatibility fixes.', '', 'Confirm whether only one app is affected.' UNION ALL
    SELECT 'fix-iphone-app-crashing', 3, 'Reinstall after backup', 'Confirm important app data is synchronized, delete the app, reinstall it from the App Store, and sign in again.', 'A clean app installation opens correctly.', 'Deleting an app can remove data stored only in that app.', 'Contact the developer if the reinstalled app still fails.' UNION ALL
    SELECT 'fix-ubuntu-wifi-not-connecting', 1, 'Check wireless settings', 'Confirm Airplane Mode is off, Wi-Fi is enabled, and the network appears in Ubuntu settings.', 'The wireless network is visible and available to select.', '', 'Forget and reconnect to the saved network.' UNION ALL
    SELECT 'fix-ubuntu-wifi-not-connecting', 2, 'Inspect the wireless device', 'Open Terminal and run nmcli device.', 'A wireless interface appears in the device list.', 'This command is for Ubuntu.', 'Restart NetworkManager if the interface is present but disconnected.' UNION ALL
    SELECT 'fix-ubuntu-wifi-not-connecting', 3, 'Restart NetworkManager', 'Run sudo systemctl restart NetworkManager, then reconnect to Wi-Fi.', 'Ubuntu can reconnect to the network.', 'This command is for Ubuntu. Do not download random driver packages.', 'Use official Ubuntu driver tools if no wireless device appears.' UNION ALL
    SELECT 'fix-ubuntu-package-update-errors', 1, 'Close other package tools', 'Close Software Updater, Ubuntu Software, Synaptic, and other terminal package commands.', 'Only one package manager process is running.', 'Do not delete package lock files manually.', 'Confirm internet access before retrying.' UNION ALL
    SELECT 'fix-ubuntu-package-update-errors', 2, 'Refresh package information', 'Open Terminal and run sudo apt update. Read the final error lines carefully.', 'Ubuntu refreshes package information or reports a specific error.', 'This command is for Ubuntu. Do not run commands from untrusted websites.', 'Repair interrupted configuration only when the error indicates it.' UNION ALL
    SELECT 'fix-ubuntu-package-update-errors', 3, 'Repair interrupted packages', 'Run sudo dpkg --configure -a, then sudo apt --fix-broken install, and retry sudo apt upgrade.', 'Interrupted configuration and dependencies are repaired.', 'These commands are for Ubuntu. Review errors before continuing.', 'Consult Ubuntu documentation for unsupported repositories or persistent errors.' UNION ALL
    SELECT 'speed-up-slow-mac', 1, 'Check storage space', 'Open Apple menu, System Settings, General, Storage and review available disk space.', 'You identify large files, downloads, or apps that can be removed safely.', 'Do not delete system folders to free space.', 'Restart the Mac after safely freeing space.' UNION ALL
    SELECT 'speed-up-slow-mac', 2, 'Review Activity Monitor', 'Open Activity Monitor, select Memory, and close only apps you recognize that use excessive resources.', 'Known resource-heavy apps no longer consume unnecessary memory.', 'Do not force quit processes you do not recognize.', 'Review Login Items if the slowdown returns after restart.' UNION ALL
    SELECT 'speed-up-slow-mac', 3, 'Update and test Safe Mode', 'Install macOS and app updates. Start in Safe Mode if the issue continues, then test after leaving Safe Mode.', 'You identify whether startup software contributes to the slowdown.', '', 'Contact Apple Support if Safe Mode does not improve repeated freezes or restarts.' UNION ALL
    SELECT 'fix-macos-update-installation-error', 1, 'Back up and prepare', 'Back up important files, confirm free storage, connect to stable internet, and disconnect unnecessary external devices.', 'The Mac is ready for a safe update retry.', 'Do not start a major repair without a verified backup.', 'Restart and retry Software Update.' UNION ALL
    SELECT 'fix-macos-update-installation-error', 2, 'Retry in Safe Mode', 'Start the Mac in Safe Mode, then retry the update from System Settings, General, Software Update.', 'The update installs without startup-software interference.', '', 'Use macOS Recovery if installation still fails.' UNION ALL
    SELECT 'fix-macos-update-installation-error', 3, 'Use recovery carefully', 'In macOS Recovery, run Disk Utility First Aid on the startup disk before retrying installation.', 'Disk checks complete and the installer can be retried.', 'Do not erase the Mac unless a verified backup exists and safer options failed.', 'Contact Apple Support for persistent recovery or firmware failures.' UNION ALL
    SELECT 'fix-wifi-keeps-disconnecting', 1, 'Identify the scope', 'Check whether one device, every wireless device, or wired devices also lose internet.', 'You separate a device Wi-Fi problem from a modem or provider problem.', '', 'Test Ethernet when possible.' UNION ALL
    SELECT 'fix-wifi-keeps-disconnecting', 2, 'Restart the network', 'Restart the modem, wait for stable lights, then restart the router and reconnect the affected device.', 'Devices reconnect without repeated disconnects.', '', 'Improve router placement if wireless devices still drop.' UNION ALL
    SELECT 'fix-wifi-keeps-disconnecting', 3, 'Improve placement and firmware', 'Place the router openly near the center of the home, test 5 GHz nearby and 2.4 GHz farther away, then install official firmware.', 'Wireless stability improves in the problem area.', 'Do not install random third-party firmware.', 'Contact the provider when Ethernet also disconnects.' UNION ALL
    SELECT 'fix-wifi-connected-no-internet', 1, 'Test the connection scope', 'Test more than one website and another device on the same network. Disable mobile data during the test.', 'You know whether the issue affects one device or every device.', '', 'Restart the affected device when only it fails.' UNION ALL
    SELECT 'fix-wifi-connected-no-internet', 2, 'Restart modem and router', 'Restart the modem, wait for stable status lights, then restart the router and test again.', 'Devices receive internet access after the network restarts.', '', 'Check the provider outage page when every device remains offline.' UNION ALL
    SELECT 'fix-wifi-connected-no-internet', 3, 'Check wired access and VPN', 'Test a computer through Ethernet, confirm the router WAN cable is connected, and temporarily disable a VPN.', 'You identify whether the problem is Wi-Fi, router, modem, provider, or VPN related.', 'Change DNS only after ordinary checks fail.', 'Contact the provider when wired and wireless devices have no internet.'
) AS seeded ON seeded.guide_slug = guides.slug
ON DUPLICATE KEY UPDATE
    step_title = VALUES(step_title), step_text = VALUES(step_text), expected_result = VALUES(expected_result), warning_text = VALUES(warning_text), recovery_text = VALUES(recovery_text);
