ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS is_published TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS featured_order INT UNSIGNED NULL;

ALTER TABLE guides
    ADD COLUMN IF NOT EXISTS is_published TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS featured_order INT UNSIGNED NULL;

ALTER TABLE downloads
    ADD COLUMN IF NOT EXISTS is_published TINYINT(1) NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS featured_order INT UNSIGNED NULL;
